// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9xowXlItL9xG3BkO6fNfHsrq2EggQlQ',
    appId: '1:608836737387:web:8535e313332621bfda942e',
    messagingSenderId: '608836737387',
    projectId: 'chatter-71b62',
    authDomain: 'chatter-71b62.firebaseapp.com',
    storageBucket: 'chatter-71b62.appspot.com',
    measurementId: 'G-8ZVDRL6KSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8eihAHn5iG2q-guzUlU05Hpp1VT51tRI',
    appId: '1:608836737387:android:8b615832ac343e5dda942e',
    messagingSenderId: '608836737387',
    projectId: 'chatter-71b62',
    storageBucket: 'chatter-71b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHGFR9kZ98xWU4HKV48OBgHf2XBb8KIOQ',
    appId: '1:608836737387:ios:facd37781ee4f29bda942e',
    messagingSenderId: '608836737387',
    projectId: 'chatter-71b62',
    storageBucket: 'chatter-71b62.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHGFR9kZ98xWU4HKV48OBgHf2XBb8KIOQ',
    appId: '1:608836737387:ios:1927993b970e731fda942e',
    messagingSenderId: '608836737387',
    projectId: 'chatter-71b62',
    storageBucket: 'chatter-71b62.appspot.com',
    iosBundleId: 'com.example.chatter.RunnerTests',
  );
}
